### ISSUE TITLE
[feature] 마이페이지 UI, AI 브랜딩 프롬프트

### ISSUE THREAD

**Issue by leejin-rho** [team-Reddi/reddi-client#102]
## 📌 구현 기능

- 남은 API 연결, UI 수정

### 🛠 작업 내용

- [x] 마이페이지 로그인 알림 UI 수정
- [x] #110 마이페이지 AI 브랜딩 프롬프트 UI 구현
- [x] 마이페이지 AI 브랜딩 프롬프트 API 연결
- [x] #103 북마크 API 연결 및 detail page 연결
- [x] #104 로그인 정보 로컬스토리지 저장

### 💬 기타 사항

-
