### ISSUE TITLE
[feature] UI 수정 및 로직 설정

### ISSUE THREAD

**Issue by leejin-rho** [team-Reddi/reddi-client#28]
## 📌 구현 기능

- 기존 디자인 수정 및 로직 설정

### 🛠 작업 내용

- [x] #29 브랜딩, 마케팅화면 padding조정 및 스타일 디테일 수정
- [x] #30 로그인 배너 설정
- [x] #35 AI 브랜딩 바뀐 UI 수정
- [x]  #37  AI 브랜딩 Loading UI 구현
- [x] #35 AI 브랜딩 로직 설정
- [x] #32 검색창 submit연결

### 💬 기타 사항

- 일단 백엔드가 api 주기 전까지
