### ISSUE TITLE
[feature] 브랜드, 마케팅 상세 페이지 detail 수정, 바뀐 UI 수정

### ISSUE THREAD

**Issue by leejin-rho** [team-Reddi/reddi-client#51]
## 📌 구현 기능

- 기존 디자인 수정 및 로직 수정, animation 적용

### 🛠 작업 내용

- [x] #57 브랜드 detail 간격 수정
- [x] #54 마케팅 detail 배경 반투명하게 수정
- [x] #54 마케팅 detail 페이지 이전 버튼 없애고 위에 navbar 유지하는 형식
- [x] #54 브랜드 detail 페이지 이전 버튼 없애고 위에 navbar 유지하는 형식
- [x] #58 마케팅 detail 간격 수정
- [x] #53 마케팅 리스트 subtitle -> 산업군 태그로 변경
- [ ] 마케팅 detail 이미지 width, height에 따라 크기 조정 **/보류**
- [x] #58 마케팅, 브랜드 북마크 floating button 추가
- [x] 브랜드 리스트 수정된 UI 적용
- [x] #AI 브랜딩 이전 버튼 제거
- [x] reddi 누르면 홈으로
- [x] #56 detail-> 이전 페이지 이동 시 현재페이지 유지되게
- [x] #60 marketing/brand detail 페이지 조회수(viewCount) 올라가게
- [x] #62 home api 연동

### 💬 기타 사항

- 해커톤 전까지..!?
