### ISSUE TITLE
[feature] 스켈레톤 UI 추가, 마뀐 마케팅 component UI 구현, 산업군 추가

### ISSUE THREAD

**Issue by leejin-rho** [team-Reddi/reddi-client#69]
## 📌 구현 기능

- API 명세서 바탕으로 response 

### 🛠 작업 내용

- [x] #68 홈 스켈레톤 UI 추가
- [x] #78 마케팅 스켈레톤 UI 추가
- [x] #78 브랜드 스켈레톤 UI 추가
- [x] #74 마케팅 바뀐 디자인 component 구현
- [x] #74 브랜드 바뀐 디자인 component 구현
- [x] #71 홈 디자인 산업군 추가
- [x] #74 마케팅, 브랜드 bookmark 추가

  
### 💬 기타 사항

- 해커톤날 끝낼까?!
