### ISSUE TITLE
[feature] Search, AI Branding API 연결, 홈, 마케팅, 테그 UI 수정

### ISSUE THREAD

**Issue by leejin-rho** [team-Reddi/reddi-client#79]
## 📌 구현 기능

- 남은 API 연결, UI 수정

### 🛠 작업 내용

- [x] #94 검색바 API 연결
- [x] #80 검색 결과 API 연결
- [x] #93 AI브랜딩 결과 API 연결
- [x] AI 브랜딩 제목 UI 수정
- [x] #88 회원가입 슬라이드바 위치 고정
- [x] home marketing component 북마크 숨김
- [x] #85 테그 눌렀을때 아래 컴포넌트 위치 바뀌지 않도록 수정
- [x] #85 categories 한줄만 유지하도록 수정 (+버튼)
- [x] 플로팅 버튼 위치 변경
- [ ] 검색결과 페이지네이션 //보류
- [x] #88 search- hot referenceAPI 연결

### 💬 기타 사항

- 수요일까지...!? (2/31)
